create own portfolio
DecodersCommunity/portfolio-builder pull request #48
Opened 2022-10-12 03:22 UTC by sangam-verma9

2022-10-12 04:20 UTC, isyneha commented on Your Portfolio/sangam-verma9.html
> +Footer
Remove these lines

2022-10-12 04:21 UTC, isyneha requested changes
Please remove these extra lines from above and below.

2022-10-12 04:21 UTC, isyneha commented on Your Portfolio/sangam-verma9.html
> +Skip to content
REmove Line No- 1 to 30

2022-10-16 05:05 UTC, sangam-verma9 commented on Your Portfolio/sangam-verma9.html
> +Skip to content
ok maam done

2022-10-27 06:20 UTC, isyneha approved these changes
LGTM, Approving

2022-10-27 06:20 UTC, merged